# This is a basic workflow to help you get started with Actions

name: Deploy Omnomnomica to dev

on: workflow_dispatch
  # pull_request:
  #   branches: [ dev ]

jobs:
  deploy-website:
    name: "Deploy website"
    runs-on: ubuntu-latest
    env:
      aws_access_key_id: '${{ secrets.S3_USER_AWS_ACCESS_KEY_ID }}'
      aws_secret_access_key: '${{ secrets.S3_USER_AWS_SECRET_ACCESS_KEY }}'
      AWS_DEFAULT_REGION: 'us-west-2'
    steps:
      - uses: actions/checkout@v2
      - name: Terraform plan
        run: |
          cd ./scripts
          chmod 777 ./plan.sh
          ./plan.sh
      - name: Terraform apply
        run: |
          cd ./scripts
          chmod 777 ./apply.sh
          ./apply.sh
